// ============================================================
// exercicios.js – Banco completo de exercícios
// ============================================================
const EXERCICIOS_DB = [
  // ===== PEITO =====
  { id:'pe01', nome:'Supino Reto com Barra',        grupo:'Peito',    subgrupo:'Peitoral Maior (med)', equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pe02', nome:'Supino Reto com Halteres',     grupo:'Peito',    subgrupo:'Peitoral Maior (med)', equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pe03', nome:'Supino Inclinado Barra',        grupo:'Peito',    subgrupo:'Peitoral Maior (sup)', equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pe04', nome:'Supino Inclinado Halteres',     grupo:'Peito',    subgrupo:'Peitoral Maior (sup)', equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pe05', nome:'Supino Declinado Barra',        grupo:'Peito',    subgrupo:'Peitoral Maior (inf)', equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pe06', nome:'Supino Declinado Halteres',     grupo:'Peito',    subgrupo:'Peitoral Maior (inf)', equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pe07', nome:'Crucifixo Reto',                grupo:'Peito',    subgrupo:'Peitoral (isolamento)', equip:'Halteres',    tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pe08', nome:'Crucifixo Inclinado',           grupo:'Peito',    subgrupo:'Peitoral Superior',    equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pe09', nome:'Crossover (Polia Alta)',        grupo:'Peito',    subgrupo:'Peitoral (isolamento)', equip:'Polia',       tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pe10', nome:'Crossover (Polia Baixa)',       grupo:'Peito',    subgrupo:'Peitoral Superior',    equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pe11', nome:'Crossover (Polia Média)',       grupo:'Peito',    subgrupo:'Peitoral Geral',       equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pe12', nome:'Flexão de Braços',              grupo:'Peito',    subgrupo:'Peitoral Geral',       equip:'Peso Corporal',tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pe13', nome:'Flexão Diamante',               grupo:'Peito',    subgrupo:'Peitoral + Tríceps',   equip:'Peso Corporal',tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pe14', nome:'Flexão Inclinada',              grupo:'Peito',    subgrupo:'Peitoral Inferior',    equip:'Peso Corporal',tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pe15', nome:'Pullover',                      grupo:'Peito',    subgrupo:'Peitoral + Grande Dorsal', equip:'Halteres', tipo:'Isolado',   nivel:'Intermediário', video:'' },
  { id:'pe16', nome:'Pec Deck / Voador',             grupo:'Peito',    subgrupo:'Peitoral (isolamento)', equip:'Máquina',    tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pe17', nome:'Chest Press Máquina',           grupo:'Peito',    subgrupo:'Peitoral Geral',       equip:'Máquina',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pe18', nome:'Supino Guilhotina',             grupo:'Peito',    subgrupo:'Peitoral Superior',    equip:'Barra',        tipo:'Composto',   nivel:'Avançado', video:'' },
  { id:'pe19', nome:'Supino Neutro Halteres',        grupo:'Peito',    subgrupo:'Peitoral + Ombro',     equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pe20', nome:'Mergulho no Paralelo (Peito)',  grupo:'Peito',    subgrupo:'Peitoral + Tríceps',   equip:'Paralela',     tipo:'Composto',   nivel:'Intermediário', video:'' },

  // ===== COSTAS =====
  { id:'co01', nome:'Barra Fixa Pronada',            grupo:'Costas',   subgrupo:'Grande Dorsal',        equip:'Barra Fixa',   tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'co02', nome:'Barra Fixa Supinada',           grupo:'Costas',   subgrupo:'Grande Dorsal + Bíceps', equip:'Barra Fixa', tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'co03', nome:'Puxada Frontal Barra Larga',    grupo:'Costas',   subgrupo:'Grande Dorsal',        equip:'Polia',        tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'co04', nome:'Puxada Frontal Barra Fechada',  grupo:'Costas',   subgrupo:'Grande Dorsal + Bíceps', equip:'Polia',      tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'co05', nome:'Puxada Neutra',                 grupo:'Costas',   subgrupo:'Grande Dorsal',        equip:'Polia',        tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'co06', nome:'Remada Curvada Barra',          grupo:'Costas',   subgrupo:'Grande Dorsal + Trapézio', equip:'Barra',    tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'co07', nome:'Remada Curvada Halteres',       grupo:'Costas',   subgrupo:'Grande Dorsal',        equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'co08', nome:'Remada Unilateral',             grupo:'Costas',   subgrupo:'Grande Dorsal',        equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'co09', nome:'Remada Cavalinho (T-Bar)',      grupo:'Costas',   subgrupo:'Grande Dorsal + Trapézio', equip:'Barra',    tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'co10', nome:'Remada Sentado Polia Baixa',    grupo:'Costas',   subgrupo:'Grande Dorsal + Romboides', equip:'Polia',   tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'co11', nome:'Levantamento Terra',            grupo:'Costas',   subgrupo:'Eretores + Glúteo',    equip:'Barra',        tipo:'Composto',   nivel:'Avançado', video:'' },
  { id:'co12', nome:'Levantamento Terra Romeno',     grupo:'Costas',   subgrupo:'Eretores + Isquios',   equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'co13', nome:'Hiperextensão Lombar',          grupo:'Costas',   subgrupo:'Eretores da Coluna',   equip:'Banco',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'co14', nome:'Good Morning',                  grupo:'Costas',   subgrupo:'Eretores + Isquios',   equip:'Barra',        tipo:'Composto',   nivel:'Avançado', video:'' },
  { id:'co15', nome:'Serrote',                       grupo:'Costas',   subgrupo:'Grande Dorsal',        equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'co16', nome:'Pull-over Polia',               grupo:'Costas',   subgrupo:'Grande Dorsal',        equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'co17', nome:'Remada Alta (Upright Row)',     grupo:'Costas',   subgrupo:'Trapézio + Deltóide',  equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'co18', nome:'Encolhimento de Ombros Barra',  grupo:'Costas',   subgrupo:'Trapézio Superior',    equip:'Barra',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'co19', nome:'Encolhimento Halteres',         grupo:'Costas',   subgrupo:'Trapézio Superior',    equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'co20', nome:'Face Pull',                     grupo:'Costas',   subgrupo:'Trapézio + Romboides', equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },

  // ===== OMBROS =====
  { id:'om01', nome:'Desenvolvimento Arnold',        grupo:'Ombros',   subgrupo:'Deltóide Geral',       equip:'Halteres',     tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'om02', nome:'Desenvolvimento Halteres',      grupo:'Ombros',   subgrupo:'Deltóide Anterior',    equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'om03', nome:'Desenvolvimento Barra (Frente)', grupo:'Ombros',  subgrupo:'Deltóide Anterior',    equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'om04', nome:'Desenvolvimento Barra (Nuca)',  grupo:'Ombros',   subgrupo:'Deltóide Posterior',   equip:'Barra',        tipo:'Composto',   nivel:'Avançado', video:'' },
  { id:'om05', nome:'Elevação Lateral',              grupo:'Ombros',   subgrupo:'Deltóide Lateral',     equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'om06', nome:'Elevação Lateral Polia',        grupo:'Ombros',   subgrupo:'Deltóide Lateral',     equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'om07', nome:'Elevação Frontal',              grupo:'Ombros',   subgrupo:'Deltóide Anterior',    equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'om08', nome:'Elevação Frontal Barra',        grupo:'Ombros',   subgrupo:'Deltóide Anterior',    equip:'Barra',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'om09', nome:'Crucifixo Invertido',           grupo:'Ombros',   subgrupo:'Deltóide Posterior',   equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'om10', nome:'Crucifixo Invertido Polia',     grupo:'Ombros',   subgrupo:'Deltóide Posterior',   equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'om11', nome:'Puxada pelo Queixo',            grupo:'Ombros',   subgrupo:'Trapézio + Deltóide',  equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'om12', nome:'Shoulder Press Máquina',        grupo:'Ombros',   subgrupo:'Deltóide Geral',       equip:'Máquina',      tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'om13', nome:'Press Militar em Pé',           grupo:'Ombros',   subgrupo:'Deltóide + Core',      equip:'Barra',        tipo:'Composto',   nivel:'Avançado', video:'' },
  { id:'om14', nome:'Elevação Lateral Debruçado',    grupo:'Ombros',   subgrupo:'Deltóide Posterior',   equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },

  // ===== BÍCEPS =====
  { id:'bi01', nome:'Rosca Direta Barra',            grupo:'Bíceps',   subgrupo:'Bíceps Braquial',      equip:'Barra',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi02', nome:'Rosca Direta Halteres',         grupo:'Bíceps',   subgrupo:'Bíceps Braquial',      equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi03', nome:'Rosca Alternada',               grupo:'Bíceps',   subgrupo:'Bíceps Braquial',      equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi04', nome:'Rosca Martelo',                 grupo:'Bíceps',   subgrupo:'Braquiorradial',       equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi05', nome:'Rosca Scott Barra',             grupo:'Bíceps',   subgrupo:'Bíceps Braquial (inf)', equip:'Barra+Banco', tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi06', nome:'Rosca Scott Halteres',          grupo:'Bíceps',   subgrupo:'Bíceps Braquial',      equip:'Halteres+Banco',tipo:'Isolado',   nivel:'Iniciante', video:'' },
  { id:'bi07', nome:'Rosca Concentrada',             grupo:'Bíceps',   subgrupo:'Bíceps (pico)',        equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi08', nome:'Rosca Inclinada',               grupo:'Bíceps',   subgrupo:'Bíceps Braquial (cabeça longa)', equip:'Halteres', tipo:'Isolado', nivel:'Iniciante', video:'' },
  { id:'bi09', nome:'Rosca Polia Baixa',             grupo:'Bíceps',   subgrupo:'Bíceps Braquial',      equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi10', nome:'Rosca 21s',                     grupo:'Bíceps',   subgrupo:'Bíceps Completo',      equip:'Barra',        tipo:'Isolado',    nivel:'Intermediário', video:'' },
  { id:'bi11', nome:'Rosca Inversa',                 grupo:'Bíceps',   subgrupo:'Braquiorradial',       equip:'Barra',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'bi12', nome:'Rosca Zottman',                 grupo:'Bíceps',   subgrupo:'Bíceps + Antebraço',   equip:'Halteres',     tipo:'Isolado',    nivel:'Intermediário', video:'' },

  // ===== TRÍCEPS =====
  { id:'tr01', nome:'Tríceps Pulley Barra Reta',     grupo:'Tríceps',  subgrupo:'Tríceps Braquial',     equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'tr02', nome:'Tríceps Pulley Corda',          grupo:'Tríceps',  subgrupo:'Tríceps Braquial',     equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'tr03', nome:'Tríceps Pulley Barra V',        grupo:'Tríceps',  subgrupo:'Tríceps Braquial',     equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'tr04', nome:'Tríceps Testa (Barra)',         grupo:'Tríceps',  subgrupo:'Tríceps (cab. longa)', equip:'Barra',        tipo:'Isolado',    nivel:'Intermediário', video:'' },
  { id:'tr05', nome:'Tríceps Testa (Halteres)',      grupo:'Tríceps',  subgrupo:'Tríceps (cab. longa)', equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'tr06', nome:'Tríceps Francês',               grupo:'Tríceps',  subgrupo:'Tríceps (cab. longa)', equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'tr07', nome:'Tríceps Coice (Kickback)',      grupo:'Tríceps',  subgrupo:'Tríceps (cab. lateral)', equip:'Halteres',   tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'tr08', nome:'Mergulho Banco',                grupo:'Tríceps',  subgrupo:'Tríceps + Peito',      equip:'Banco',        tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'tr09', nome:'Mergulho Paralelas (Tríceps)',  grupo:'Tríceps',  subgrupo:'Tríceps + Peito',      equip:'Paralela',     tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'tr10', nome:'Close Grip Bench Press',        grupo:'Tríceps',  subgrupo:'Tríceps + Peito',      equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'tr11', nome:'Tríceps Extensão Polia Alta',   grupo:'Tríceps',  subgrupo:'Tríceps (cab. longa)', equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'tr12', nome:'Skullcrusher EZ',               grupo:'Tríceps',  subgrupo:'Tríceps Braquial',     equip:'Barra EZ',     tipo:'Isolado',    nivel:'Intermediário', video:'' },

  // ===== PERNAS =====
  { id:'pg01', nome:'Agachamento Livre',             grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pg02', nome:'Agachamento Sumô',              grupo:'Pernas',   subgrupo:'Quadríceps + Adutores', equip:'Barra/Halter', tipo:'Composto',  nivel:'Intermediário', video:'' },
  { id:'pg03', nome:'Agachamento Frontal',           grupo:'Pernas',   subgrupo:'Quadríceps (énfase)',  equip:'Barra',        tipo:'Composto',   nivel:'Avançado', video:'' },
  { id:'pg04', nome:'Agachamento Goblet',            grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pg05', nome:'Leg Press 45°',                 grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Máquina',      tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pg06', nome:'Leg Press Horizontal',          grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Máquina',      tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pg07', nome:'Extensora',                     grupo:'Pernas',   subgrupo:'Quadríceps',           equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg08', nome:'Flexora Deitada',               grupo:'Pernas',   subgrupo:'Isquiotibiais',        equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg09', nome:'Flexora Sentada',               grupo:'Pernas',   subgrupo:'Isquiotibiais',        equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg10', nome:'Stiff Barra',                   grupo:'Pernas',   subgrupo:'Isquiotibiais + Glúteo', equip:'Barra',      tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pg11', nome:'Stiff Halteres',                grupo:'Pernas',   subgrupo:'Isquiotibiais + Glúteo', equip:'Halteres',   tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pg12', nome:'Avanço (Lunge) Caminhando',     grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pg13', nome:'Avanço Estático',               grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'pg14', nome:'Afundo Búlgaro',                grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Halteres',     tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pg15', nome:'Panturrilha em Pé',             grupo:'Pernas',   subgrupo:'Gastrocnêmio',         equip:'Máquina/Barra',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg16', nome:'Panturrilha Sentado',           grupo:'Pernas',   subgrupo:'Sóleo',                equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg17', nome:'Adutor Máquina',                grupo:'Pernas',   subgrupo:'Adutores',             equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg18', nome:'Abdutor Máquina',               grupo:'Pernas',   subgrupo:'Abdutores',            equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg19', nome:'Hip Thrust Barra',              grupo:'Pernas',   subgrupo:'Glúteo Máximo',        equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'pg20', nome:'Cadeira Abdutora',              grupo:'Pernas',   subgrupo:'Glúteo Médio',         equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg21', nome:'Glúteo 4 apoios (kickback)',    grupo:'Pernas',   subgrupo:'Glúteo Máximo',        equip:'Polia/Corporal',tipo:'Isolado',   nivel:'Iniciante', video:'' },
  { id:'pg22', nome:'Agachamento Búlgaro Barra',     grupo:'Pernas',   subgrupo:'Quadríceps + Glúteo',  equip:'Barra',        tipo:'Composto',   nivel:'Avançado', video:'' },
  { id:'pg23', nome:'Leg Curl Unilateral',           grupo:'Pernas',   subgrupo:'Isquiotibiais',        equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg24', nome:'Glúteo no Crossover',           grupo:'Pernas',   subgrupo:'Glúteo Máximo',        equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pg25', nome:'Pistol Squat',                  grupo:'Pernas',   subgrupo:'Quadríceps (unilateral)', equip:'Peso Corporal', tipo:'Composto', nivel:'Avançado', video:'' },

  // ===== ABDÔMEN =====
  { id:'ab01', nome:'Abdominal Crunch',              grupo:'Abdômen',  subgrupo:'Reto Abdominal',       equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'ab02', nome:'Crunch na Polia',               grupo:'Abdômen',  subgrupo:'Reto Abdominal',       equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'ab03', nome:'Elevação de Pernas Deitado',    grupo:'Abdômen',  subgrupo:'Reto Abdominal (inf)', equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'ab04', nome:'Elevação de Pernas Barra Fixa', grupo:'Abdômen',  subgrupo:'Reto Abdominal',       equip:'Barra Fixa',   tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'ab05', nome:'Prancha Frontal',               grupo:'Abdômen',  subgrupo:'Core Geral',           equip:'Peso Corporal',tipo:'Isométrico', nivel:'Iniciante', video:'' },
  { id:'ab06', nome:'Prancha Lateral',               grupo:'Abdômen',  subgrupo:'Oblíquos',             equip:'Peso Corporal',tipo:'Isométrico', nivel:'Iniciante', video:'' },
  { id:'ab07', nome:'Abdominal Oblíquo',             grupo:'Abdômen',  subgrupo:'Oblíquos',             equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'ab08', nome:'Russian Twist',                 grupo:'Abdômen',  subgrupo:'Oblíquos',             equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'ab09', nome:'Rotação de Tronco Polia',       grupo:'Abdômen',  subgrupo:'Oblíquos',             equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'ab10', nome:'Dead Bug',                      grupo:'Abdômen',  subgrupo:'Core Estabilizador',   equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'ab11', nome:'Ab Wheel (Roda Abdominal)',     grupo:'Abdômen',  subgrupo:'Core Geral',           equip:'Roda',         tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'ab12', nome:'Dragon Flag',                   grupo:'Abdômen',  subgrupo:'Core Avançado',        equip:'Banco',        tipo:'Isolado',    nivel:'Avançado', video:'' },

  // ===== GLÚTEOS =====
  { id:'gl01', nome:'Hip Thrust Smith',              grupo:'Glúteos',  subgrupo:'Glúteo Máximo',        equip:'Smith',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'gl02', nome:'Stiff Unilateral',              grupo:'Glúteos',  subgrupo:'Glúteo + Isquios',     equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'gl03', nome:'Elevação Pélvica',              grupo:'Glúteos',  subgrupo:'Glúteo Máximo',        equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'gl04', nome:'Coice de Burro',                grupo:'Glúteos',  subgrupo:'Glúteo Máximo',        equip:'Polia',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'gl05', nome:'Abdução de Quadril Deitado',    grupo:'Glúteos',  subgrupo:'Glúteo Médio',         equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },

  // ===== ANTEBRAÇO =====
  { id:'an01', nome:'Rosca Punho Barra',             grupo:'Antebraço', subgrupo:'Flexores do Punho',   equip:'Barra',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'an02', nome:'Rosca Punho Inversa',           grupo:'Antebraço', subgrupo:'Extensores do Punho',  equip:'Barra',        tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'an03', nome:'Extensão de Punho Halteres',    grupo:'Antebraço', subgrupo:'Extensores do Punho',  equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'an04', nome:'Flexão de Punho Halteres',      grupo:'Antebraço', subgrupo:'Flexores do Punho',    equip:'Halteres',     tipo:'Isolado',    nivel:'Iniciante', video:'' },

  // ===== PANTURRILHA (EXTRA) =====
  { id:'pa01', nome:'Panturrilha no Leg Press',      grupo:'Pernas',   subgrupo:'Gastrocnêmio',         equip:'Máquina',      tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pa02', nome:'Panturrilha Unilateral',        grupo:'Pernas',   subgrupo:'Gastrocnêmio',         equip:'Peso Corporal',tipo:'Isolado',    nivel:'Iniciante', video:'' },
  { id:'pa03', nome:'Panturrilha Donkey (Burrinho)', grupo:'Pernas',   subgrupo:'Gastrocnêmio',         equip:'Máquina/Parceiro', tipo:'Isolado', nivel:'Intermediário', video:'' },

  // ===== CARDIO =====
  { id:'cd01', nome:'Corrida na Esteira',            grupo:'Cardio',   subgrupo:'Resistência Aeróbica', equip:'Esteira',      tipo:'Cardio',     nivel:'Iniciante', video:'' },
  { id:'cd02', nome:'Bicicleta Ergométrica',         grupo:'Cardio',   subgrupo:'Resistência Aeróbica', equip:'Bicicleta',    tipo:'Cardio',     nivel:'Iniciante', video:'' },
  { id:'cd03', nome:'Elíptico',                      grupo:'Cardio',   subgrupo:'Baixo Impacto',        equip:'Máquina',      tipo:'Cardio',     nivel:'Iniciante', video:'' },
  { id:'cd04', nome:'Pular Corda',                   grupo:'Cardio',   subgrupo:'Coordenação + Cardio', equip:'Corda',        tipo:'Cardio',     nivel:'Intermediário', video:'' },
  { id:'cd05', nome:'Remo Seco',                     grupo:'Cardio',   subgrupo:'Resistência Muscular', equip:'Máquina',      tipo:'Cardio',     nivel:'Intermediário', video:'' },

  // ===== FUNCIONAIS/OLÍMPICOS =====
  { id:'fn01', nome:'Clean e Jerk (Arremesso)',       grupo:'Funcional', subgrupo:'Corpo Inteiro',      equip:'Barra',        tipo:'Olímpico',   nivel:'Avançado', video:'' },
  { id:'fn02', nome:'Snatch (Arranque)',              grupo:'Funcional', subgrupo:'Corpo Inteiro',      equip:'Barra',        tipo:'Olímpico',   nivel:'Avançado', video:'' },
  { id:'fn03', nome:'Clean (Arrancada)',              grupo:'Funcional', subgrupo:'Corpo Inteiro',      equip:'Barra',        tipo:'Olímpico',   nivel:'Avançado', video:'' },
  { id:'fn04', nome:'Kettlebell Swing',               grupo:'Funcional', subgrupo:'Glúteo + Lombar',   equip:'Kettlebell',   tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'fn05', nome:'Turkish Get Up',                grupo:'Funcional', subgrupo:'Core + Ombro',       equip:'Kettlebell',   tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'fn06', nome:'Farmer Walk',                   grupo:'Funcional', subgrupo:'Core + Trapézio',    equip:'Halteres',     tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'fn07', nome:'Burpee',                        grupo:'Funcional', subgrupo:'Corpo Inteiro',      equip:'Peso Corporal',tipo:'Composto',   nivel:'Iniciante', video:'' },
  { id:'fn08', nome:'Push Press',                    grupo:'Funcional', subgrupo:'Ombro + Pernas',     equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
  { id:'fn09', nome:'Thruster',                      grupo:'Funcional', subgrupo:'Corpo Inteiro',      equip:'Barra',        tipo:'Composto',   nivel:'Intermediário', video:'' },
];

// ===== TÉCNICAS DE TREINO =====
const TECNICAS_DB = [
  { id:'t01', nome:'Série Simples', categoria:'Básica',
    descricao:'Séries realizadas de forma independente com intervalo de descanso entre elas.',
    aplicacao:'Todos os exercícios e níveis.',
    intensidade:'Qualquer % do 1RM',
    series:'3–5', descanso:'60–180s', nivel:'Iniciante' },
  { id:'t02', nome:'Bi-Set Agonista', categoria:'Intensidade',
    descricao:'Dois exercícios para o mesmo grupo muscular executados sem descanso entre eles.',
    aplicacao:'Ex: Supino + Crucifixo | Puxada + Remada',
    intensidade:'65–80% 1RM',
    series:'3–4', descanso:'90–120s após o par', nivel:'Intermediário' },
  { id:'t03', nome:'Super-Set Antagonista', categoria:'Intensidade',
    descricao:'Dois exercícios para grupos antagonistas sem descanso.',
    aplicacao:'Ex: Bíceps + Tríceps | Peito + Costas',
    intensidade:'70–80% 1RM',
    series:'3–4', descanso:'60–90s após o par', nivel:'Intermediário' },
  { id:'t04', nome:'Tri-Set', categoria:'Intensidade',
    descricao:'Três exercícios consecutivos para o mesmo grupo muscular sem descanso.',
    aplicacao:'Ex: Supino + Crucifixo + Mergulho',
    intensidade:'60–75% 1RM',
    series:'3–4', descanso:'120s após o trio', nivel:'Intermediário' },
  { id:'t05', nome:'Giant Set', categoria:'Intensidade',
    descricao:'4 ou mais exercícios para o mesmo grupo sem descanso.',
    aplicacao:'Treinos de alto volume / emagrecimento',
    intensidade:'50–70% 1RM',
    series:'3', descanso:'120–180s após o bloco', nivel:'Avançado' },
  { id:'t06', nome:'Drop Set', categoria:'Intensidade',
    descricao:'Executa a série até a falha, reduz 20–30% da carga imediatamente e continua.',
    aplicacao:'Último exercício por grupo muscular',
    intensidade:'Iniciando em 80% 1RM → drops',
    series:'1–2 (com 2–4 drops cada)', descanso:'180s após a série', nivel:'Avançado' },
  { id:'t07', nome:'Rest-Pause', categoria:'Avançada',
    descricao:'Executa 6–8 reps, descansa 15–20s, continua até a falha novamente (2–3 pausas).',
    aplicacao:'Qualquer exercício composto ou isolado',
    intensidade:'80–90% 1RM',
    series:'2–3', descanso:'3–5 min entre séries', nivel:'Avançado' },
  { id:'t08', nome:'Cluster Set', categoria:'Avançada',
    descricao:'Microintervalos de 10–30s dentro de cada série para manter potência alta.',
    aplicacao:'Exercícios de força e potência',
    intensidade:'85–95% 1RM',
    series:'4–6', descanso:'3–5 min entre clusters', nivel:'Avançado' },
  { id:'t09', nome:'Pirâmide Crescente', categoria:'Básica',
    descricao:'Carga aumenta e repetições diminuem a cada série.',
    aplicacao:'Aquecimento progressivo, qualquer exercício',
    intensidade:'60→70→80→90% 1RM',
    series:'4–5', descanso:'90–120s', nivel:'Iniciante' },
  { id:'t10', nome:'Pirâmide Decrescente', categoria:'Básica',
    descricao:'Começa pesado (baixas reps) e alivia a carga progressivamente.',
    aplicacao:'Força + hipertrofia combinados',
    intensidade:'90→80→70→60% 1RM',
    series:'4–5', descanso:'120–180s', nivel:'Intermediário' },
  { id:'t11', nome:'Pirâmide Dupla (Triangular)', categoria:'Avançada',
    descricao:'Crescente até o pico + decrescente voltando ao ponto de partida.',
    aplicacao:'Alta densidade de volume',
    intensidade:'60→90→60% 1RM',
    series:'5–7', descanso:'90s', nivel:'Avançado' },
  { id:'t12', nome:'Pré-Exaustão', categoria:'Intensidade',
    descricao:'Exercício isolado antes do composto para pré-fadigar o músculo-alvo.',
    aplicacao:'Ex: Crucifixo → Supino | Extensora → Agachamento',
    intensidade:'Isolado 70% | Composto 75–80% 1RM',
    series:'3–4', descanso:'0s entre par, 120s após', nivel:'Intermediário' },
  { id:'t13', nome:'Pós-Exaustão', categoria:'Intensidade',
    descricao:'Exercício composto seguido de isolado para finalizar o músculo-alvo.',
    aplicacao:'Ex: Supino → Crucifixo',
    intensidade:'Composto 80% | Isolado 65% 1RM',
    series:'3–4', descanso:'0s entre par, 120s após', nivel:'Intermediário' },
  { id:'t14', nome:'Séries 21s', categoria:'Intensidade',
    descricao:'7 reps na metade inferior do movimento + 7 na superior + 7 completas = 21.',
    aplicacao:'Clássico para bíceps; adaptável a outros grupos',
    intensidade:'50–60% 1RM',
    series:'3–4', descanso:'90s', nivel:'Intermediário' },
  { id:'t15', nome:'Oclusão Vascular (BFR)', categoria:'Avançada',
    descricao:'Restrição parcial do fluxo sanguíneo com garrote/elástico (60–80% oclusão arterial).',
    aplicacao:'Membros: bíceps, quadríceps, panturrilha',
    intensidade:'20–40% 1RM – altas reps (15–30)',
    series:'4 (1×30 + 3×15)', descanso:'30–60s', nivel:'Avançado' },
  { id:'t16', nome:'Contração Isométrica', categoria:'Especializada',
    descricao:'Contração estática sem movimento articular.',
    aplicacao:'Prancha, pausa no ponto de maior tensão',
    intensidade:'Máxima tensão por 20–60s',
    series:'3–5', descanso:'60–90s', nivel:'Iniciante' },
  { id:'t17', nome:'Ênfase Excêntrica (Negativa)', categoria:'Avançada',
    descricao:'Fase excêntrica lenta (3–6s) para maximizar dano muscular.',
    aplicacao:'Qualquer exercício',
    intensidade:'80–110% 1RM (com auxílio no concêntrico)',
    series:'3–4', descanso:'3–5 min', nivel:'Avançado' },
  { id:'t18', nome:'Tensão Contínua (TUT)', categoria:'Intensidade',
    descricao:'Sem pausa nos pontos de menor tensão; tempo sob tensão elevado (40–70s/série).',
    aplicacao:'Isolados, máquinas',
    intensidade:'60–70% 1RM',
    series:'3–4', descanso:'90s', nivel:'Intermediário' },
  { id:'t19', nome:'Myo-Reps', categoria:'Avançada',
    descricao:'Série ativadora até falha + microintervalos de 3–5 respirações + mini-séries de 3–5 reps.',
    aplicacao:'Exercícios isolados para hipertrofia eficiente',
    intensidade:'65–75% 1RM',
    series:'2–4 ativadoras', descanso:'2–3 min após bloco', nivel:'Avançado' },
  { id:'t20', nome:'Mechanical Drop Set', categoria:'Avançada',
    descricao:'Muda a pegada/posição (vantagem mecânica) sem reduzir carga ao falhar.',
    aplicacao:'Ex: Rosca inclinada → alternada → martelo',
    intensidade:'70–80% 1RM',
    series:'1–2 (3 posições cada)', descanso:'180s', nivel:'Avançado' },
  { id:'t21', nome:'Circuito', categoria:'Condicionamento',
    descricao:'Exercícios consecutivos sem descanso entre eles; descanso ao final do circuito.',
    aplicacao:'Emagrecimento, condicionamento geral',
    intensidade:'50–65% 1RM',
    series:'3–5 voltas', descanso:'60–90s por volta', nivel:'Iniciante' },
  { id:'t22', nome:'AMRAP (As Many Reps As Possible)', categoria:'Condicionamento',
    descricao:'Máximo de repetições/séries em tempo determinado.',
    aplicacao:'CrossFit, treinos metabólicos',
    intensidade:'50–70% 1RM',
    series:'1 bloco por exercício', descanso:'Por bloco temporal', nivel:'Intermediário' },
  { id:'t23', nome:'Forced Reps', categoria:'Avançada',
    descricao:'Repetições além da falha com auxílio de um parceiro.',
    aplicacao:'Últimas 2–3 reps após a falha',
    intensidade:'85–90% 1RM',
    series:'2–3', descanso:'3–5 min', nivel:'Avançado' },
  { id:'t24', nome:'Séries Descendentes de Volume', categoria:'Especializada',
    descricao:'Redução gradual do número de repetições mantendo carga.',
    aplicacao:'Ex: 15→12→10→8 reps, mesma carga',
    intensidade:'65–75% 1RM',
    series:'4', descanso:'90s', nivel:'Intermediário' },
  { id:'t25', nome:'Wave Loading', categoria:'Avançada',
    descricao:'Ondulação de cargas/reps em ondas: Ex: 6-4-2 / 6-4-2 aumentando levemente.',
    aplicacao:'Força máxima, exercícios compostos',
    intensidade:'80–95% 1RM',
    series:'2 ondas (6 séries total)', descanso:'3–5 min', nivel:'Avançado' },
];

// ===== PROTOCOLOS DE PERIODIZAÇÃO =====
const PROTOCOLOS_DB = [
  {
    id:'p01', nome:'Linear Simples',
    descricao:'Carga aumenta progressivamente semana a semana. Mais adequado para iniciantes e intermediários.',
    fase: [
      { sem:'1–4',  obj:'Adaptação',  series:'3', reps:'12–15', int:'60–65%' },
      { sem:'5–8',  obj:'Hipertrofia',series:'4', reps:'8–12',  int:'70–75%' },
      { sem:'9–12', obj:'Força',      series:'4', reps:'4–6',   int:'80–85%' },
      { sem:'13',   obj:'Deload',     series:'2', reps:'12–15', int:'50–60%' },
    ],
    ref:'Zatsiorsky & Kraemer (2006)',
  },
  {
    id:'p02', nome:'Ondulante Diário (DUP)',
    descricao:'Alteração de estímulo diário: força, hipertrofia e potência/resistência em dias diferentes.',
    fase: [
      { sem:'Dia 1', obj:'Força',       series:'4', reps:'3–5',   int:'85–90%' },
      { sem:'Dia 2', obj:'Hipertrofia', series:'4', reps:'8–10',  int:'70–75%' },
      { sem:'Dia 3', obj:'Resistência', series:'3', reps:'12–15', int:'60–65%' },
    ],
    ref:'Zourdos et al. (2016); Colquhoun et al. (2017)',
  },
  {
    id:'p03', nome:'5/3/1 (Wendler)',
    descricao:'4 semanas cíclicas com aumento progressivo + deload. Foco em levantamentos principais.',
    fase: [
      { sem:'Semana 1', obj:'Volume',  series:'3', reps:'5-5-5+',   int:'65-75-85%' },
      { sem:'Semana 2', obj:'Intensidade', series:'3', reps:'3-3-3+', int:'70-80-90%' },
      { sem:'Semana 3', obj:'Deload',   series:'3', reps:'5-3-1+',   int:'75-85-95%' },
      { sem:'Semana 4', obj:'Deload',   series:'3', reps:'5-5-5',    int:'40-50-60%' },
    ],
    ref:'Wendler (2009)',
  },
  {
    id:'p04', nome:'Método Conjugado (Westside)',
    descricao:'Max Effort (ME) e Dynamic Effort (DE) alternados. Força máxima + velocidade.',
    fase: [
      { sem:'ME Upper', obj:'Força Máxima',  series:'3–5', reps:'1–3', int:'90–100%' },
      { sem:'DE Upper', obj:'Velocidade',    series:'8–10', reps:'2–3', int:'55–65%' },
      { sem:'ME Lower', obj:'Força Máxima',  series:'3–5', reps:'1–3', int:'90–100%' },
      { sem:'DE Lower', obj:'Velocidade',    series:'8–10', reps:'2–3', int:'55–65%' },
    ],
    ref:'Simmons (1999)',
  },
  {
    id:'p05', nome:'Texas Method',
    descricao:'Volume na segunda, recuperação na quarta e intensidade na sexta. Para intermediários.',
    fase: [
      { sem:'Volume (Seg)',    obj:'Acúmulo',    series:'5', reps:'5', int:'90% do 5RM' },
      { sem:'Recuperação (Qua)', obj:'Deload',  series:'2', reps:'5', int:'80%' },
      { sem:'Intensidade (Sex)', obj:'PR',      series:'1', reps:'5', int:'Novo máximo' },
    ],
    ref:'Rippetoe & Baker (2013)',
  },
  {
    id:'p06', nome:'Método de Israetel (RIR/Volume)',
    descricao:'Baseado em Reps in Reserve (RIR) e volume de manutenção → desenvolvimento.',
    fase: [
      { sem:'MEV (vol. mínimo)', obj:'Manutenção', series:'~MEV', reps:'8–12', int:'RIR 3–4' },
      { sem:'MAV (vol. ótimo)',  obj:'Hipertrofia', series:'~MAV', reps:'8–12', int:'RIR 2–3' },
      { sem:'MRV (vol. máximo)', obj:'Overreach',   series:'~MRV', reps:'8–12', int:'RIR 0–1' },
      { sem:'Deload',            obj:'Recuperação',  series:'MEV/2', reps:'12–15', int:'RIR 4–5' },
    ],
    ref:'Israetel, Hoffmann & Smith (2019) – Scientific Principles of Hypertrophy',
  },
  {
    id:'p07', nome:'Bloco de Periodização',
    descricao:'Blocos sequenciais: Acumulação → Transmutação → Realização.',
    fase: [
      { sem:'Acumulação (4 sem)',   obj:'Volume base', series:'4–5', reps:'8–12', int:'65–75%' },
      { sem:'Transmutação (3 sem)', obj:'Força',       series:'4',   reps:'4–6',  int:'78–85%' },
      { sem:'Realização (2 sem)',   obj:'Pico',        series:'3',   reps:'1–3',  int:'90–100%' },
      { sem:'Deload (1 sem)',       obj:'Recuperação', series:'2',   reps:'10–12',int:'50–60%' },
    ],
    ref:'Issurin (2008)',
  },
  {
    id:'p08', nome:'GZCLP (Zac Cain)',
    descricao:'3 tiers de exercícios com progressão diferente. T1: compostos pesados, T2: compostos auxiliares, T3: isolados.',
    fase: [
      { sem:'T1 Compostos', obj:'Força', series:'5×3 / 6×2', reps:'3–5', int:'85–92%' },
      { sem:'T2 Auxiliares', obj:'Hipertrofia', series:'3×10', reps:'10', int:'70–75%' },
      { sem:'T3 Isolados', obj:'Volume', series:'3×15+', reps:'15–25', int:'50–60%' },
    ],
    ref:'Cain (2012) – GZCL Method',
  },
];

// ===== HELPERS =====
function getGrupos() {
  return [...new Set(EXERCICIOS_DB.map(e => e.grupo))].sort();
}
function getExerciciosPorGrupo(grupo) {
  return EXERCICIOS_DB.filter(e => e.grupo === grupo);
}
function getExercicioById(id) {
  return EXERCICIOS_DB.find(e => e.id === id);
}
function searchExercicios(query) {
  const q = query.toLowerCase();
  return EXERCICIOS_DB.filter(e => e.nome.toLowerCase().includes(q) || e.grupo.toLowerCase().includes(q) || e.subgrupo.toLowerCase().includes(q));
}
